/home/wooyeon/Multimodal-Augmentation/GMMIX/CLIP/clip/clip.py:23: UserWarning: PyTorch version 1.7.1 or higher is recommended
  warnings.warn("PyTorch version 1.7.1 or higher is recommended")
loading annotations into memory...
Done (t=0.66s)
creating index...
index created!
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
length of train set :  118287
Traceback (most recent call last):
  File "/home/wooyeon/Multimodal-Augmentation/GMMIX/clip_mod_sph.py", line 932, in <module>
    flickrtest          = FlickerDataset('/home/wooyeon/Multimodal-Augmentation/GMMIX/dataset/flicker/flickr30k_images/flickr30k_images',transform=preprocess).filter_df("test")
  File "/home/wooyeon/Multimodal-Augmentation/GMMIX/dataset.py", line 14, in __init__
    self.caption_df = pd.read_csv(os.path.join(self.folder_path,'results.csv')).dropna(axis=0).drop_duplicates(subset="image_name")
  File "/home/iknow/anaconda3/envs/ma/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/iknow/anaconda3/envs/ma/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/iknow/anaconda3/envs/ma/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/iknow/anaconda3/envs/ma/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    return parser.read(nrows)
  File "/home/iknow/anaconda3/envs/ma/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/iknow/anaconda3/envs/ma/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2